language: node_js
node_js:
  - 14

services:
  - mongodb
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/tamashii-test -f ./server/Dockerfile.dev ./server

script:
  - >-
    docker run --network host
    --env MONGO_HOST=$MONGO_HOST
    --env MONGO_PORT=$MONGO_PORT
    --env MONGO_DB=$MONGO_DB
    --env GRAPHQL_PORT=$GRAPHQL_PORT
    --env CI=true
    $DOCKER_USERNAME/tamashii-test
    npm test -- --coverage

after_success:
  - docker build -t $DOCKER_USERNAME/tamashii-client ./client
  - docker build -t $DOCKER_USERNAME/tamashii-nginx ./nginx
  - docker build -t $DOCKER_USERNAME/tamashii-server ./server
  # Login into the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push to DockerHUB
  - docker push $DOCKER_USERNAME/tamashii-client
  - docker push $DOCKER_USERNAME/tamashii-nginx
  - docker push $DOCKER_USERNAME/tamashii-server
