language: generic
node_js:
  - 14

services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/$API_NAME -f ./server/Dockerfile ./server
  - docker build -t $DOCKER_USERNAME/$INT_NAME -f ./server/Dockerfile.test ./server


before_script:
  - docker network create $NETWORK_NAME
  - sleep 5
  - >-
    docker run -d
    --network $NETWORK_NAME
    --env PORT=$API_PORT
    --name $API_NAME
    --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    --env AWS_BUCKET=$AWS_BUCKET
    --env PAYPAL_CLIENT=$PAYPAL_CLIENT
    --env PAYPAL_SECRET=$PAYPAL_SECRET
    --env PAYPAL_PAYMENT_API=$PAYPAL_PAYMENT_API
    $DOCKER_USERNAME/$API_NAME

script:
  - docker ps -a
  - >-
    docker run
    --network $NETWORK_NAME
    --CI=true
    --env API_HOST=$API_NAME
    --env MONGO=$MONGO
    --env PORT=$API_PORT
    --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    --env AWS_BUCKET=$AWS_BUCKET
    --env PAYPAL_CLIENT=$PAYPAL_CLIENT
    --env PAYPAL_SECRET=$PAYPAL_SECRET
    --env PAYPAL_PAYMENT_API=$PAYPAL_PAYMENT_API
    $DOCKER_USERNAME/$INT_NAME

after_success:
  - docker build -t $DOCKER_USERNAME/tamashii-client ./client
  - docker build -t $DOCKER_USERNAME/tamashii-nginx ./nginx
  - docker build -t $DOCKER_USERNAME/tamashii-server ./server
  # Login into the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push to DockerHUB
  - docker push $DOCKER_USERNAME/tamashii-client
  - docker push $DOCKER_USERNAME/tamashii-nginx
  - docker push $DOCKER_USERNAME/tamashii-server
