language: generic
node_js:
  - 14

services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/tamashii-server -f ./server/Dockerfile ./server
  - docker build -t $DOCKER_USERNAME/tamashii-server-test -f ./server/Dockerfile.test ./server


before_script:
  - sleep 5
  - >-
    docker run -d
    --network host
    --env PORT=$SERVER_PORT
    --hostname tamashii-server
    $DOCKER_USERNAME/tamashii-server


script:
  - docker ps -a
  - docker inspect tamashii-server
  - >-
    docker run
    --env CI=true
    --env AWS_ACCESS_KEY=$AWS_ACCESS_KEY
    --env AWS_BUCKET=$AWS_BUCKET
    --env MONGO=$MONGO
    --env PORT=$SERVER_PORT
    $DOCKER_USERNAME/tamashii-server-test
  - docker ps -a

after_success:
  - docker build -t $DOCKER_USERNAME/tamashii-client ./client
  - docker build -t $DOCKER_USERNAME/tamashii-nginx ./nginx
  - docker build -t $DOCKER_USERNAME/tamashii-server ./server
  # Login into the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push to DockerHUB
  - docker push $DOCKER_USERNAME/tamashii-client
  - docker push $DOCKER_USERNAME/tamashii-nginx
  - docker push $DOCKER_USERNAME/tamashii-server
