version: '3' 
services:
  mongo:
    image: mongo:latest
    container_name: 'mongo'
    restart: always
    volumes:
      - ./mongoVolune:/data/db
    ports: 
      - '27017:27017'
    logging:
      driver: none
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client/:/app
      - /app/.next
    ports:
      - '3000:3000'
  server:
    restart: always
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server/:/app
    environment:
      - MONGO_HOST=mongodb://mongo/database
      - MONGO_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    ports:
      - '4000:4000'
    links:
      - mongo
