version: '3.1'
services:
  nginx:
    container_name: tamashii-nginx
    image: jairanpo/tamashii-nginx
    ports:
      - '80:80'
    links:
      - client
      - api
  client:
    container_name: tamashii-client
    image: jairanpo/tamashii-client
  api:
    image: jairanpo/tamashii-api
    container_name: tamashii-api
    env_file:
      - /server/env/production.env
