enum Role {
    ADMIN
    CLIENT
    EDITOR
}

type User{
    id: ID
    firstName: String
    middleName: String
    lastName: String
    secondLastName: String
    password: String
    email: String
    birthday: String
    cellphone: String
    role: Role
    mapOfAddresses: MapOfAddresses
}

input UserInput{
    id: ID
    firstName: String!
    middleName: String
    lastName: String!
    secondLastName: String!
    password: String!
    email: String!
    birthday: String!
    cellphone: String!
    role: String!
    mapOfAddresses: MapOfAddressesInput
}

input SignupInput{
    firstName: String!
    middleName: String
    lastName: String!
    secondLastName: String!
    password: String!
    email: String!
    birthday: String!
    cellphone: String!
    mapOfAddresses: MapOfAddressesInput!
}

type AdminSignup{
    firstName: String
    middleName: String
    lastName: String
    secondLastName: String
    password: String
    email: String
    cellphone: String
    role: String
}

input AdminSignupInput{
    firstName: String!
    middleName: String
    lastName: String!
    secondLastName: String!
    password: String!
    email: String!
    cellphone: String!
}

input LoginInput{
    email: String!
    password: String!
}

type ResetPassword{
    email: String!
    password: String!
    confirmPassword: String!
}

input UpdateUserInput{
    id: ID
    firstName: String
    middleName: String
    lastName: String
    secondLastName: String
    cellphone: String
    address: [AddressInput!]
}

type QueryUser{
    id: ID
    firstName: String
    middleName: String
    lastName: String
    secondLastName: String
    email: String
    birthday: String
    cellphone: String
    role: Role
    mapOfAddresses: MapOfAddresses
}


type AuthUser {
    token: String!
    userInfo: QueryUser
    expiresIn: Int!
}


#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

union UserAuthResult = SuccessfulUserAuth | InvalidUserAuth
type InvalidUserAuth{
    status: String
    message: String
    listOfErrors: [String]
}
type SuccessfulUserAuth{
    status: String
    message: String
    authInfo: AuthUser
}

#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

union UserResult = Me | InvalidUser


type Me{
    status: String
    message: String
    me: QueryUser
}

type InvalidUser{
    status: String
    message: String
    listOfErrors: [String]
}

#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

input ResetPasswordInput{
    email: String!
    password: String!
    confirmPassword: String!
}

type Query {
    me: UserResult
    login(input: LoginInput!): UserAuthResult
}

type Mutation {
    signup(input: SignupInput!): AuthUser!
    adminSignup(input: AdminSignupInput!): AuthUser!
    deleteUser( id : ID!) : String
    updateUser( input: UpdateUserInput ) : User
    resetPassword(input: ResetPasswordInput) : User
}