mutation deleteCart{
    deleteCart{
        __typename
        ... on DeletedCart{
            status
            message
            listOfProducts{
                name
            }
        }
    }
}