query queryAllAvailableProducts{
    queryAllAvailableProducts{
        id
        code
        purchaseLimit
        name
        listOfImages
        price{
            amount
            currency
        }
    }
}
