mutation signup($input: SignupInput!){
    signup(input: $input){
        token
        userInfo{
            id
            firstName
            middleName
            lastName
            secondLastName
        }
        expiresIn
    }
}

