mutation signup($input: SignupInput!){
    signup(input: $input){
        token
        user{
            firstName
            middleName
            lastName
            secondLastName
        }
    }
}

