type Product {
    id: ID
    name: String
    price: Price
    description: String
    code: String
    stock: Int
    available: Boolean
    publishDate: String
    listOfImages: [String]
    purchaseLimit: Int
    listOfTags: [String]
}

input ProductInput {
    name: String!
    price: PriceInput!
    description: String!
    code: String!
    stock: Int!
    purchaseLimit: Int!
    available: Boolean!
    publishDate: String!
    listOfImages: [String!]!
    listOfTags: [String!]!
}

type Price{
    amount: Float
    currency: String
}

input PriceInput{
    amount: Float!
    currency: String!
}

extend type Query {
    queryListOfProducts:[Product]
    queryProduct(id : ID!) : Product
}

extend type Mutation {
    createProduct(input: ProductInput!) : Product
    updateProduct( id: ID!, input: ProductInput) : Product
    deleteProduct( id : ID! ): String
}


